template = templateSVM(...
     'KernelFunction', 'polynomial', ...
     'PolynomialOrder', 3, ...
     'KernelScale', 21.199, ...
     'BoxConstraint', 0.17871, ...
     'Standardize', true);
 Classes = {'cel','cla','flu','gac','gel','org',...
     'pia','sax','tru','vio','voi'};
[Md2, paramResults] = fitcecoc(...
    TrainFeatures, ...
    trainLabels, ...
    'Learners', template, ...
    'Coding', 'onevsone', ...
    'ClassNames',categorical(Classes), ...
    'OptimizeHyperparameters','auto', ...
    'HyperparameterOptimizationOptions', ...
    struct('MaxObjectiveEvaluations',20, ...
    'SaveIntermediateResults',true));

optimal = bestPoint(BayesoptResults)
